### ISSUE TITLE
Getting error using cli object has no attribute 'arn'

### ISSUE THREAD

**Issue by hendrixroa** [Skyscanner/LambdaGuard#3] opened 2019-09-10 18:21 UTC
When I run `lambdaguard --function 'myarfunction' --profile myprofile --region region --verbose` i getting those errors:
`/lambdaguard/core/Lambda.py", line 184, in report
    'role': self.role.arn.full,
AttributeError: 'NoneType' object has no attribute 'arn'`

Should I install some dependency?

**Comment by adeptex** [comment] 2019-09-11 11:25
Hi @hendrixroa, there should probably be more error handling around that... 

the `--function` argument should be like `arn:aws:...` is that the format you're using for `myarfunction`?

**Comment by adeptex** [comment] 2019-09-21 21:35
@hendrixroa i can't reproduce your issue. can you please post your `lambdaguard.log`?

**Comment by hendrixroa** [comment] 2019-09-26 00:38
@adeptex I'll test it again

**Comment by hendrixroa** [comment] 2019-09-26 00:48
I installed the last version of pip package, see screenshot

![Screen Shot 2019-09-25 at 8 43 49 PM](https://user-images.githubusercontent.com/8594048/65649669-88f07980-dfd5-11e9-9a95-6284e3c53b7e.png)

- Possible solution?
The IAM policy of LambdaGuard should have access to lambda?
In another words which permission should have the lambdaGuard profile

**Comment by adeptex** [comment] 2019-10-13 18:31
Hi @hendrixroa you can use `make aws` to setup AWS access. Basically it just needs `arn:aws:iam::aws:policy/ReadOnlyAccess` to make everything work without having to specify explicit permissions for each service.

Although in your case it seems that your Lambda function doesn't have an IAM role defined. I will implement an exception handler for that

**Comment by adeptex** [comment] 2019-10-13 21:51
Fixed in https://github.com/Skyscanner/LambdaGuard/commit/f6b7916d1f5c5379f0f9f3c973c805067784aa65

**Closed by adeptex** 2019-10-13 21:51 UTC
